(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.
Require bool.Bool.
Require real.Real.
Require real.RealInfix.
Require real.FromInt.
Require Jessie_memory_model.

(* Why3 assumption *)
Definition unit := unit.

Axiom usObject : Type.
Parameter usObject_WhyType : WhyType usObject.
Existing Instance usObject_WhyType.

Axiom interface : Type.
Parameter interface_WhyType : WhyType interface.
Existing Instance interface_WhyType.

Parameter usDeterrenceM_tag: (Jessie_memory_model.tag_id usObject).

Parameter usObject_tag: (Jessie_memory_model.tag_id usObject).

Axiom usDeterrenceM_parenttag_Object : (Jessie_memory_model.parenttag
  usDeterrenceM_tag usObject_tag).

Parameter usDeterrence_DEFENDER_COST: R.

Parameter usDeterrence_INITIAL_VALUE: R.

Parameter usDeterrence_RETALIATION_COST: R.

Parameter usDeterrence_RETALIATION_EFFECT: R.

Parameter usDeterrence_mutateProbability: R.

Parameter usDeterrence_tag: (Jessie_memory_model.tag_id usObject).

Axiom usDeterrence_parenttag_Object : (Jessie_memory_model.parenttag
  usDeterrence_tag usObject_tag).

Parameter usException_tag: (Jessie_memory_model.tag_id usObject).

Axiom usException_parenttag_Object : (Jessie_memory_model.parenttag
  usException_tag usObject_tag).

Parameter usFilterOutputStream_tag: (Jessie_memory_model.tag_id usObject).

Parameter usOutputStream_tag: (Jessie_memory_model.tag_id usObject).

Axiom usFilterOutputStream_parenttag_OutputStream : (Jessie_memory_model.parenttag
  usFilterOutputStream_tag usOutputStream_tag).

Parameter usInputStream_tag: (Jessie_memory_model.tag_id usObject).

Axiom usInputStream_parenttag_Object : (Jessie_memory_model.parenttag
  usInputStream_tag usObject_tag).

(* Why3 assumption *)
Definition usNon_null_DeterrenceM (x_4:(Jessie_memory_model.pointer
  usObject)) (usObject_alloc_table:(Jessie_memory_model.alloc_table
  usObject)): Prop :=
  ((-1%Z)%Z <= (Jessie_memory_model.offset_max usObject_alloc_table x_4))%Z.

(* Why3 assumption *)
Definition usNon_null_Object (x_6:(Jessie_memory_model.pointer usObject))
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject)): Prop :=
  (0%Z <= (Jessie_memory_model.offset_max usObject_alloc_table x_6))%Z.

(* Why3 assumption *)
Definition usNon_null_StringM (x_0:(Jessie_memory_model.pointer usObject))
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject)): Prop :=
  ((-1%Z)%Z <= (Jessie_memory_model.offset_max usObject_alloc_table x_0))%Z.

(* Why3 assumption *)
Definition usNon_null_byteM (x_3:(Jessie_memory_model.pointer usObject))
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject)): Prop :=
  ((-1%Z)%Z <= (Jessie_memory_model.offset_max usObject_alloc_table x_3))%Z.

(* Why3 assumption *)
Definition usNon_null_charM (x_1:(Jessie_memory_model.pointer usObject))
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject)): Prop :=
  ((-1%Z)%Z <= (Jessie_memory_model.offset_max usObject_alloc_table x_1))%Z.

(* Why3 assumption *)
Definition usNon_null_doubleM (x_2:(Jessie_memory_model.pointer usObject))
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject)): Prop :=
  ((-1%Z)%Z <= (Jessie_memory_model.offset_max usObject_alloc_table x_2))%Z.

(* Why3 assumption *)
Definition usNon_null_intM (x_5:(Jessie_memory_model.pointer usObject))
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject)): Prop :=
  ((-1%Z)%Z <= (Jessie_memory_model.offset_max usObject_alloc_table x_5))%Z.

Axiom usObject_int : ((Jessie_memory_model.int_of_tag usObject_tag) = 1%Z).

Parameter usObject_of_pointer_address: (Jessie_memory_model.pointer unit) ->
  (Jessie_memory_model.pointer usObject).

Axiom usObject_of_pointer_address_of_pointer_addr : forall (p:(Jessie_memory_model.pointer
  usObject)),
  (p = (usObject_of_pointer_address (Jessie_memory_model.pointer_address p))).

Axiom usObject_parenttag_bottom : (Jessie_memory_model.parenttag usObject_tag
  (Jessie_memory_model.bottom_tag : (Jessie_memory_model.tag_id usObject))).

Axiom usObject_tags : forall (x:(Jessie_memory_model.pointer usObject)),
  forall (usObject_tag_table:(Jessie_memory_model.tag_table usObject)),
  (Jessie_memory_model.instanceof usObject_tag_table x usObject_tag).

Parameter usOutputStreamWriter_tag: (Jessie_memory_model.tag_id usObject).

Axiom usOutputStreamWriter_parenttag_Object : (Jessie_memory_model.parenttag
  usOutputStreamWriter_tag usObject_tag).

Axiom usOutputStream_parenttag_Object : (Jessie_memory_model.parenttag
  usOutputStream_tag usObject_tag).

Parameter usPrintStream_tag: (Jessie_memory_model.tag_id usObject).

Axiom usPrintStream_parenttag_FilterOutputStream : (Jessie_memory_model.parenttag
  usPrintStream_tag usFilterOutputStream_tag).

Parameter usStringBuffer_tag: (Jessie_memory_model.tag_id usObject).

Axiom usStringBuffer_parenttag_Object : (Jessie_memory_model.parenttag
  usStringBuffer_tag usObject_tag).

Parameter usStringM_tag: (Jessie_memory_model.tag_id usObject).

Axiom usStringM_parenttag_Object : (Jessie_memory_model.parenttag
  usStringM_tag usObject_tag).

Parameter usString_tag: (Jessie_memory_model.tag_id usObject).

Axiom usString_parenttag_Object : (Jessie_memory_model.parenttag usString_tag
  usObject_tag).

Parameter usSystem_err: (Jessie_memory_model.pointer usObject).

Parameter usSystem_in: (Jessie_memory_model.pointer usObject).

Parameter usSystem_out: (Jessie_memory_model.pointer usObject).

Parameter usSystem_tag: (Jessie_memory_model.tag_id usObject).

Axiom usSystem_parenttag_Object : (Jessie_memory_model.parenttag usSystem_tag
  usObject_tag).

Parameter usThrowable_tag: (Jessie_memory_model.tag_id usObject).

Axiom usThrowable_parenttag_Object : (Jessie_memory_model.parenttag
  usThrowable_tag usObject_tag).

(* Why3 assumption *)
Definition attribution_valid (this_0:(Jessie_memory_model.pointer usObject))
  (usDeterrence_ATTRIBUTION_PROBABILITY:R): Prop :=
  (0%R <= usDeterrence_ATTRIBUTION_PROBABILITY)%R /\
  (usDeterrence_ATTRIBUTION_PROBABILITY <= 1%R)%R.

Parameter byteM_tag: (Jessie_memory_model.tag_id usObject).

Axiom byteM_parenttag_Object : (Jessie_memory_model.parenttag byteM_tag
  usObject_tag).

Parameter charM_tag: (Jessie_memory_model.tag_id usObject).

Axiom charM_parenttag_Object : (Jessie_memory_model.parenttag charM_tag
  usObject_tag).

Parameter doubleM_tag: (Jessie_memory_model.tag_id usObject).

Axiom doubleM_parenttag_Object : (Jessie_memory_model.parenttag doubleM_tag
  usObject_tag).

(* Why3 assumption *)
Definition expectedValue_logic (intensity_2:Z) (numIgnores:Z)
  (numRetaliates:Z) (usATTRIBUTION_PROBABILITY_0:R)
  (usRETALIATION_EFFECT:R): R :=
  (((Reals.Raxioms.IZR (intensity_2 + 1%Z)%Z) * ((Reals.Raxioms.IZR numIgnores) + ((Reals.Raxioms.IZR numRetaliates) * ((1%R - usATTRIBUTION_PROBABILITY_0)%R - (usRETALIATION_EFFECT * usATTRIBUTION_PROBABILITY_0)%R)%R)%R)%R)%R / (Reals.Raxioms.IZR (numIgnores + numRetaliates)%Z))%R.

Parameter intM_tag: (Jessie_memory_model.tag_id usObject).

Axiom intM_parenttag_Object : (Jessie_memory_model.parenttag intM_tag
  usObject_tag).

Parameter interface_tag: (Jessie_memory_model.tag_id interface).

Axiom interface_int : ((Jessie_memory_model.int_of_tag interface_tag) = 1%Z).

Parameter interface_of_pointer_address: (Jessie_memory_model.pointer unit) ->
  (Jessie_memory_model.pointer interface).

Axiom interface_of_pointer_address_of_pointer_addr : forall (p:(Jessie_memory_model.pointer
  interface)),
  (p = (interface_of_pointer_address (Jessie_memory_model.pointer_address p))).

Axiom interface_parenttag_bottom : (Jessie_memory_model.parenttag
  interface_tag (Jessie_memory_model.bottom_tag : (Jessie_memory_model.tag_id
  interface))).

Axiom interface_tags : forall (x:(Jessie_memory_model.pointer interface)),
  forall (interface_tag_table:(Jessie_memory_model.tag_table interface)),
  (Jessie_memory_model.instanceof interface_tag_table x interface_tag).

(* Why3 assumption *)
Definition irrational_valid (this_1:(Jessie_memory_model.pointer usObject))
  (usDeterrence_IRRATIONAL_PROBABILITY:R): Prop :=
  (0%R <= usDeterrence_IRRATIONAL_PROBABILITY)%R /\
  (usDeterrence_IRRATIONAL_PROBABILITY <= 1%R)%R.

(* Why3 assumption *)
Definition left_valid_struct_Object (p:(Jessie_memory_model.pointer
  usObject)) (a:Z) (usObject_alloc_table:(Jessie_memory_model.alloc_table
  usObject)): Prop := ((Jessie_memory_model.offset_min usObject_alloc_table
  p) <= a)%Z.

(* Why3 assumption *)
Definition left_valid_struct_interface (p:(Jessie_memory_model.pointer
  interface)) (a:Z) (interface_alloc_table:(Jessie_memory_model.alloc_table
  interface)): Prop := ((Jessie_memory_model.offset_min interface_alloc_table
  p) <= a)%Z.

(* Why3 assumption *)
Definition state_valid (states_0:(Jessie_memory_model.pointer usObject))
  (state:(Jessie_memory_model.pointer usObject)) (index:Z)
  (usObject_alloc_table_at_L:(Jessie_memory_model.alloc_table usObject))
  (intM_intP_at_L:(Jessie_memory_model.memory usObject Z))
  (usDeterrenceM_DeterrenceP_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (doubleM_doubleP_at_L:(Jessie_memory_model.memory usObject R))
  (usDeterrence_retaliationTable_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_numRetaliates_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_numIgnores_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_index_at_L:(Jessie_memory_model.memory usObject Z)): Prop :=
  (Jessie_memory_model.valid usObject_alloc_table_at_L state) /\
  (((Jessie_memory_model.select usDeterrenceM_DeterrenceP_at_L
  (Jessie_memory_model.shift states_0
  (Jessie_memory_model.select usDeterrence_index_at_L state))) = state) /\
  (((Jessie_memory_model.select usDeterrence_index_at_L state) = index) /\
  ((Jessie_memory_model.valid usObject_alloc_table_at_L
  (Jessie_memory_model.select usDeterrence_numIgnores_at_L state)) /\
  ((((Jessie_memory_model.offset_max usObject_alloc_table_at_L
  (Jessie_memory_model.select usDeterrence_numIgnores_at_L
  state)) + 1%Z)%Z = 10%Z) /\ ((forall (j:Z), ((0%Z <= j)%Z /\
  (j < 10%Z)%Z) -> (1%Z <= (Jessie_memory_model.select intM_intP_at_L
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numIgnores_at_L
  state) j)))%Z) /\ ((Jessie_memory_model.valid usObject_alloc_table_at_L
  (Jessie_memory_model.select usDeterrence_numRetaliates_at_L state)) /\
  ((((Jessie_memory_model.offset_max usObject_alloc_table_at_L
  (Jessie_memory_model.select usDeterrence_numRetaliates_at_L
  state)) + 1%Z)%Z = 10%Z) /\ ((forall (j_0:Z), ((0%Z <= j_0)%Z /\
  (j_0 < 10%Z)%Z) -> (1%Z <= (Jessie_memory_model.select intM_intP_at_L
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numRetaliates_at_L
  state) j_0)))%Z) /\ ((Jessie_memory_model.valid usObject_alloc_table_at_L
  (Jessie_memory_model.select usDeterrence_retaliationTable_at_L state)) /\
  ((((Jessie_memory_model.offset_max usObject_alloc_table_at_L
  (Jessie_memory_model.select usDeterrence_retaliationTable_at_L
  state)) + 1%Z)%Z = 10%Z) /\ forall (j_1:Z), ((0%Z <= j_1)%Z /\
  (j_1 < 10%Z)%Z) ->
  ((0%R <= (Jessie_memory_model.select doubleM_doubleP_at_L
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_retaliationTable_at_L
  state) j_1)))%R /\ ((Jessie_memory_model.select doubleM_doubleP_at_L
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_retaliationTable_at_L
  state) j_1)) < 1%R)%R))))))))))).

(* Why3 assumption *)
Definition me_valid (this:(Jessie_memory_model.pointer usObject))
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject))
  (intM_intP:(Jessie_memory_model.memory usObject Z))
  (usDeterrenceM_DeterrenceP:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (doubleM_doubleP:(Jessie_memory_model.memory usObject R))
  (usDeterrence_retaliationTable:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_numRetaliates:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_numIgnores:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_index:(Jessie_memory_model.memory usObject Z))
  (usDeterrence_states:(Jessie_memory_model.pointer usObject)): Prop :=
  (state_valid usDeterrence_states this
  (Jessie_memory_model.select usDeterrence_index this) usObject_alloc_table
  intM_intP usDeterrenceM_DeterrenceP doubleM_doubleP
  usDeterrence_retaliationTable usDeterrence_numRetaliates
  usDeterrence_numIgnores usDeterrence_index).

Axiom pointer_addr_of_Object_of_pointer_address : forall (p:(Jessie_memory_model.pointer
  unit)),
  (p = (Jessie_memory_model.pointer_address (usObject_of_pointer_address p))).

Axiom pointer_addr_of_interface_of_pointer_address : forall (p:(Jessie_memory_model.pointer
  unit)),
  (p = (Jessie_memory_model.pointer_address (interface_of_pointer_address p))).

(* Why3 assumption *)
Definition right_valid_struct_Object (p:(Jessie_memory_model.pointer
  usObject)) (b:Z) (usObject_alloc_table:(Jessie_memory_model.alloc_table
  usObject)): Prop :=
  (b <= (Jessie_memory_model.offset_max usObject_alloc_table p))%Z.

(* Why3 assumption *)
Definition right_valid_struct_interface (p:(Jessie_memory_model.pointer
  interface)) (b:Z) (interface_alloc_table:(Jessie_memory_model.alloc_table
  interface)): Prop :=
  (b <= (Jessie_memory_model.offset_max interface_alloc_table p))%Z.

(* Why3 assumption *)
Definition states_initialised (states:(Jessie_memory_model.pointer usObject))
  (usObject_alloc_table_at_L:(Jessie_memory_model.alloc_table
  usObject)): Prop :=
  (((Jessie_memory_model.offset_max usObject_alloc_table_at_L
  states) + 1%Z)%Z = 100%Z) /\ (Jessie_memory_model.valid
  usObject_alloc_table_at_L states).

(* Why3 assumption *)
Definition states_valid (states_2:(Jessie_memory_model.pointer usObject))
  (usObject_alloc_table_at_L:(Jessie_memory_model.alloc_table usObject))
  (intM_intP_at_L:(Jessie_memory_model.memory usObject Z))
  (usDeterrenceM_DeterrenceP_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (doubleM_doubleP_at_L:(Jessie_memory_model.memory usObject R))
  (usDeterrence_retaliationTable_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_numRetaliates_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_numIgnores_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_index_at_L:(Jessie_memory_model.memory usObject Z)): Prop :=
  (((Jessie_memory_model.offset_max usObject_alloc_table_at_L
  states_2) + 1%Z)%Z = 100%Z) /\ ((Jessie_memory_model.valid
  usObject_alloc_table_at_L states_2) /\ ((forall (i_1:Z), forall (j_2:Z),
  ((0%Z <= i_1)%Z /\ ((i_1 < 100%Z)%Z /\ ((0%Z <= j_2)%Z /\
  ((j_2 < 100%Z)%Z /\ ~ (i_1 = j_2))))) ->
  ~ ((Jessie_memory_model.select usDeterrenceM_DeterrenceP_at_L
  (Jessie_memory_model.shift states_2
  i_1)) = (Jessie_memory_model.select usDeterrenceM_DeterrenceP_at_L
  (Jessie_memory_model.shift states_2 j_2)))) /\ ((forall (i_2:Z),
  ((0%Z <= i_2)%Z /\ (i_2 < 100%Z)%Z) ->
  ((Jessie_memory_model.select usDeterrence_index_at_L
  (Jessie_memory_model.select usDeterrenceM_DeterrenceP_at_L
  (Jessie_memory_model.shift states_2 i_2))) = i_2)) /\ forall (i_3:Z),
  ((0%Z <= i_3)%Z /\ (i_3 < 100%Z)%Z) -> (state_valid states_2
  (Jessie_memory_model.select usDeterrenceM_DeterrenceP_at_L
  (Jessie_memory_model.shift states_2 i_3)) i_3 usObject_alloc_table_at_L
  intM_intP_at_L usDeterrenceM_DeterrenceP_at_L doubleM_doubleP_at_L
  usDeterrence_retaliationTable_at_L usDeterrence_numRetaliates_at_L
  usDeterrence_numIgnores_at_L usDeterrence_index_at_L)))).

(* Why3 assumption *)
Definition states_valid_up_to (states_1:(Jessie_memory_model.pointer
  usObject)) (k:Z)
  (usObject_alloc_table_at_L:(Jessie_memory_model.alloc_table usObject))
  (intM_intP_at_L:(Jessie_memory_model.memory usObject Z))
  (usDeterrenceM_DeterrenceP_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (doubleM_doubleP_at_L:(Jessie_memory_model.memory usObject R))
  (usDeterrence_retaliationTable_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_numRetaliates_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_numIgnores_at_L:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_index_at_L:(Jessie_memory_model.memory usObject Z)): Prop :=
  (forall (i:Z), ((0%Z <= i)%Z /\ (i < k)%Z) ->
  ((Jessie_memory_model.select usDeterrence_index_at_L
  (Jessie_memory_model.select usDeterrenceM_DeterrenceP_at_L
  (Jessie_memory_model.shift states_1 i))) = i)) /\ forall (i_0:Z),
  ((0%Z <= i_0)%Z /\ (i_0 < k)%Z) -> (state_valid states_1
  (Jessie_memory_model.select usDeterrenceM_DeterrenceP_at_L
  (Jessie_memory_model.shift states_1 i_0)) i_0 usObject_alloc_table_at_L
  intM_intP_at_L usDeterrenceM_DeterrenceP_at_L doubleM_doubleP_at_L
  usDeterrence_retaliationTable_at_L usDeterrence_numRetaliates_at_L
  usDeterrence_numIgnores_at_L usDeterrence_index_at_L).

(* Why3 assumption *)
Definition strict_valid_root_Object (p:(Jessie_memory_model.pointer
  usObject)) (a:Z) (b:Z)
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject)): Prop :=
  ((Jessie_memory_model.offset_min usObject_alloc_table p) = a) /\
  ((Jessie_memory_model.offset_max usObject_alloc_table p) = b).

(* Why3 assumption *)
Definition strict_valid_root_interface (p:(Jessie_memory_model.pointer
  interface)) (a:Z) (b:Z)
  (interface_alloc_table:(Jessie_memory_model.alloc_table
  interface)): Prop := ((Jessie_memory_model.offset_min interface_alloc_table
  p) = a) /\ ((Jessie_memory_model.offset_max interface_alloc_table p) = b).

(* Why3 assumption *)
Definition strict_valid_struct_Object (p:(Jessie_memory_model.pointer
  usObject)) (a:Z) (b:Z)
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject)): Prop :=
  ((Jessie_memory_model.offset_min usObject_alloc_table p) = a) /\
  ((Jessie_memory_model.offset_max usObject_alloc_table p) = b).

(* Why3 assumption *)
Definition strict_valid_struct_interface (p:(Jessie_memory_model.pointer
  interface)) (a:Z) (b:Z)
  (interface_alloc_table:(Jessie_memory_model.alloc_table
  interface)): Prop := ((Jessie_memory_model.offset_min interface_alloc_table
  p) = a) /\ ((Jessie_memory_model.offset_max interface_alloc_table p) = b).

(* Why3 assumption *)
Definition valid_root_Object (p:(Jessie_memory_model.pointer usObject)) (a:Z)
  (b:Z) (usObject_alloc_table:(Jessie_memory_model.alloc_table
  usObject)): Prop := ((Jessie_memory_model.offset_min usObject_alloc_table
  p) <= a)%Z /\ (b <= (Jessie_memory_model.offset_max usObject_alloc_table
  p))%Z.

(* Why3 assumption *)
Definition valid_root_interface (p:(Jessie_memory_model.pointer interface))
  (a:Z) (b:Z) (interface_alloc_table:(Jessie_memory_model.alloc_table
  interface)): Prop := ((Jessie_memory_model.offset_min interface_alloc_table
  p) <= a)%Z /\ (b <= (Jessie_memory_model.offset_max interface_alloc_table
  p))%Z.

(* Why3 assumption *)
Definition valid_struct_Object (p:(Jessie_memory_model.pointer usObject))
  (a:Z) (b:Z) (usObject_alloc_table:(Jessie_memory_model.alloc_table
  usObject)): Prop := ((Jessie_memory_model.offset_min usObject_alloc_table
  p) <= a)%Z /\ (b <= (Jessie_memory_model.offset_max usObject_alloc_table
  p))%Z.

(* Why3 assumption *)
Definition valid_struct_interface (p:(Jessie_memory_model.pointer interface))
  (a:Z) (b:Z) (interface_alloc_table:(Jessie_memory_model.alloc_table
  interface)): Prop := ((Jessie_memory_model.offset_min interface_alloc_table
  p) <= a)%Z /\ (b <= (Jessie_memory_model.offset_max interface_alloc_table
  p))%Z.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Implicit Arguments mk_ref [[a]].

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:(ref a)): a :=
  match v with
  | (mk_ref x) => x
  end.

(* Why3 goal *)
Theorem WP_parameter__Deterrence_highestExpectedValue_ensures_default : forall (this_8:(Jessie_memory_model.pointer
  usObject)) (target_0:(Jessie_memory_model.pointer usObject)),
  forall (usDeterrence_states:(Jessie_memory_model.pointer usObject))
  (usDeterrence_index:(Jessie_memory_model.memory usObject Z))
  (usDeterrence_numIgnores:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_numRetaliates:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (usDeterrence_retaliationTable:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject)))
  (doubleM_doubleP:(Jessie_memory_model.memory usObject R))
  (intM_intP:(Jessie_memory_model.memory usObject Z))
  (usObject_alloc_table:(Jessie_memory_model.alloc_table usObject))
  (usDeterrence_IRRATIONAL_PROBABILITY:R)
  (usDeterrence_ATTRIBUTION_PROBABILITY:R)
  (usDeterrenceM_DeterrenceP:(Jessie_memory_model.memory usObject
  (Jessie_memory_model.pointer usObject))), ((left_valid_struct_Object
  target_0 0%Z usObject_alloc_table) /\ ((valid_struct_Object this_8 0%Z 0%Z
  usObject_alloc_table) /\ ((Jessie_memory_model.valid usObject_alloc_table
  target_0) /\ (((irrational_valid this_8
  usDeterrence_IRRATIONAL_PROBABILITY) /\ ((attribution_valid this_8
  usDeterrence_ATTRIBUTION_PROBABILITY) /\ (me_valid this_8
  usObject_alloc_table intM_intP usDeterrenceM_DeterrenceP doubleM_doubleP
  usDeterrence_retaliationTable usDeterrence_numRetaliates
  usDeterrence_numIgnores usDeterrence_index usDeterrence_states))) /\
  ((irrational_valid target_0 usDeterrence_IRRATIONAL_PROBABILITY) /\
  ((attribution_valid target_0 usDeterrence_ATTRIBUTION_PROBABILITY) /\
  (me_valid target_0 usObject_alloc_table intM_intP usDeterrenceM_DeterrenceP
  doubleM_doubleP usDeterrence_retaliationTable usDeterrence_numRetaliates
  usDeterrence_numIgnores usDeterrence_index usDeterrence_states))))))) ->
  forall (h:Z) (best_0:Z), ((forall (j_4:Z), ((0%Z <= j_4)%Z /\
  (j_4 < h)%Z) -> ((expectedValue_logic j_4
  (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numIgnores
  target_0) j_4)) (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numRetaliates
  target_0) j_4)) usDeterrence_ATTRIBUTION_PROBABILITY
  usDeterrence_RETALIATION_EFFECT) <= (expectedValue_logic best_0
  (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numIgnores
  target_0) best_0)) (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numRetaliates
  target_0) best_0)) usDeterrence_ATTRIBUTION_PROBABILITY
  usDeterrence_RETALIATION_EFFECT))%R) /\ ((exists k_0:Z, (0%Z <= k_0)%Z /\
  ((k_0 < h)%Z /\ ((expectedValue_logic k_0
  (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numIgnores
  target_0) k_0)) (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numRetaliates
  target_0) k_0)) usDeterrence_ATTRIBUTION_PROBABILITY
  usDeterrence_RETALIATION_EFFECT) = (expectedValue_logic best_0
  (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numIgnores
  target_0) best_0)) (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numRetaliates
  target_0) best_0)) usDeterrence_ATTRIBUTION_PROBABILITY
  usDeterrence_RETALIATION_EFFECT)))) /\ ((0%Z <= h)%Z /\ ((h <= 10%Z)%Z /\
  ((0%Z <= best_0)%Z /\ (best_0 < 10%Z)%Z))))) -> ((h < 10%Z)%Z -> let o :=
  (expectedValue_logic best_0 (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numIgnores
  target_0) best_0)) (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numRetaliates
  target_0) best_0)) usDeterrence_ATTRIBUTION_PROBABILITY
  usDeterrence_RETALIATION_EFFECT) in ((((irrational_valid target_0
  usDeterrence_IRRATIONAL_PROBABILITY) /\ ((attribution_valid target_0
  usDeterrence_ATTRIBUTION_PROBABILITY) /\ (me_valid target_0
  usObject_alloc_table intM_intP usDeterrenceM_DeterrenceP doubleM_doubleP
  usDeterrence_retaliationTable usDeterrence_numRetaliates
  usDeterrence_numIgnores usDeterrence_index usDeterrence_states))) /\
  (o <= (Reals.Raxioms.IZR (best_0 + 1%Z)%Z))%R) -> let o1 :=
  (expectedValue_logic h (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numIgnores
  target_0) h)) (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numRetaliates
  target_0) h)) usDeterrence_ATTRIBUTION_PROBABILITY
  usDeterrence_RETALIATION_EFFECT) in ((((irrational_valid target_0
  usDeterrence_IRRATIONAL_PROBABILITY) /\ ((attribution_valid target_0
  usDeterrence_ATTRIBUTION_PROBABILITY) /\ (me_valid target_0
  usObject_alloc_table intM_intP usDeterrenceM_DeterrenceP doubleM_doubleP
  usDeterrence_retaliationTable usDeterrence_numRetaliates
  usDeterrence_numIgnores usDeterrence_index usDeterrence_states))) /\
  (o1 <= (Reals.Raxioms.IZR (h + 1%Z)%Z))%R) -> ((o < o1)%R ->
  forall (best_01:Z), (best_01 = h) -> forall (h1:Z), (h1 = (h + 1%Z)%Z) ->
  forall (j_4:Z), ((0%Z <= j_4)%Z /\ (j_4 < h1)%Z) ->
  ((expectedValue_logic j_4 (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numIgnores
  target_0) j_4)) (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numRetaliates
  target_0) j_4)) usDeterrence_ATTRIBUTION_PROBABILITY
  usDeterrence_RETALIATION_EFFECT) <= (expectedValue_logic best_01
  (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numIgnores
  target_0) best_01)) (Jessie_memory_model.select intM_intP
  (Jessie_memory_model.shift (Jessie_memory_model.select usDeterrence_numRetaliates
  target_0) best_01)) usDeterrence_ATTRIBUTION_PROBABILITY
  usDeterrence_RETALIATION_EFFECT))%R)))).
intros this_8 target_0 usDeterrence_states usDeterrence_index
usDeterrence_numIgnores usDeterrence_numRetaliates
usDeterrence_retaliationTable doubleM_doubleP intM_intP usObject_alloc_table
usDeterrence_IRRATIONAL_PROBABILITY usDeterrence_ATTRIBUTION_PROBABILITY
usDeterrenceM_DeterrenceP (h1,(h2,(h3,((h4,(h5,h6)),(h7,(h8,h9)))))) h best_0
(h10,((k_0,(h11,(h12,h13))),(h14,(h15,(h16,h17))))) h18 o
((h19,(h20,h21)),h22) o1 ((h23,(h24,h25)),h26) h27 best_01 h28 h32 h29 j_4
(h30,h31).
rewrite h28.
fold o1.
fold o in h10.
cut((0 <= j_4 < h)%Z \/ (j_4 = h)%Z).
intro.
destruct H.
cut ((expectedValue_logic j_4
   (Jessie_memory_model.select intM_intP
      (Jessie_memory_model.shift
         (Jessie_memory_model.select usDeterrence_numIgnores target_0) j_4))
   (Jessie_memory_model.select intM_intP
      (Jessie_memory_model.shift
         (Jessie_memory_model.select usDeterrence_numRetaliates target_0) j_4))
   usDeterrence_ATTRIBUTION_PROBABILITY usDeterrence_RETALIATION_EFFECT <= o)%R).
intro.
apply Rle_trans with (r2 := o).
trivial.
auto with *.
auto.
rewrite H.
fold o1.
auto with *.
omega.

Qed.

